In [1]:
print("Hello Nitin")

Hello Nitin

In [2]:
print(("heee").count("e"))

3

In [3]:
print("Hello World")

Hello World

In [4]:
"Hello World"

'Hello World'

In [5]:
3+3

6

In [6]:
10+10

20

In [7]:
print("hello world".upper())

HELLO WORLD

In [8]:
print("hellow world".lower())

hellow world

In [9]:
print("hellow world".count("w"))

2

In [10]:
print("string".replace("i","o"))

strong

In [11]:
name = "Nitin"
age = 35
print(f"my name is {name} and my age is {age}")

my name is Nitin and my age is 35

In [12]:
print((f"total marks:{78+26+25}"))

total marks:129

In [13]:
name = "nitin"
print(f"hello,{name.capitalize()}")

hello,Nitin

In [14]:
name = "nitin"
print(f"{name.upper()}")

NITIN

In [15]:
pi = 3.14
print(f"pi rounded:{pi:.2f}")

pi rounded:3.14

In [16]:
pi = 3.14563263878896
print(f"pi rounded: {pi:.0f}")

pi rounded: 3

In [17]:
countries =['India', 'china','nepal', 'japan', 'srilanka']

In [18]:
countries

['India', 'china', 'nepal', 'japan', 'srilanka']

In [19]:
print(countries[0:2])

['India', 'china']

In [20]:
print(countries[:1])

['India']

In [21]:
print(countries[:3])

['India', 'china', 'nepal']

In [22]:
print(countries[2:4])

['nepal', 'japan']

In [23]:
print(countries[0:2:4])

['India']

In [24]:
countries
print(countries[0:4:3])

['India', 'japan']

In [25]:
countries =['India', 'china','nepal', 'japan', 'srilanka']
print(countries.append('canada'))

None

In [26]:
countries

['India', 'china', 'nepal', 'japan', 'srilanka', 'canada']

In [27]:
countries.insert(0,'west indies')

In [28]:
countries

['west indies', 'India', 'china', 'nepal', 'japan', 'srilanka', 'canada']

In [29]:
countries =['India', 'china','nepal', 'japan', 'srilanka']
    print(countries.append('canada'))

countries()

IndentationError: unexpected indent (3450672646.py, line 2)

In [ ]:
countries

['India', 'china', 'nepal', 'japan', 'srilanka', 'canada']

In [ ]:
countries.remove('india')
print(countries)

ValueError: list.remove(x): x not in list

In [ ]:
countries

['India', 'china', 'japan', 'srilanka', 'canada']

In [ ]:
countries.remove('India')
print(countries)

['china', 'japan', 'srilanka', 'canada']

In [ ]:
counting = [3,6,2,9,1,4]
counting.sort()

print(counting)

[1, 2, 3, 4, 6, 9]

In [ ]:
print(counting)

[1, 2, 3, 4, 6, 9]

In [ ]:
counting = [3,6,2,9,1,4]
counting.sort(reverse=True)
print(counting)

[9, 6, 4, 3, 2, 1]

In [ ]:
counting = [3,6,2,9,0,4]
average = sum(counting)/len(counting)
print(average)
print(len(counting))

4.0
6

In [ ]:
new_list = [1,2,3,4,5,6,7,8,9]
print(new_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
new_list_2=[1,2,3,4,5,6,7,8,9]
print(new_list_2)

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
print(new_list_2[0:5])

[1, 2, 3, 4, 5]

In [ ]:
new_list = [1,2,3,4,5,6,7,8,9]
print(new_list[0:5])

countries =['India', 'china','nepal', 'japan', 'srilanka']
new_list_2 = countries.list()

[1, 2, 3, 4, 5]

AttributeError: 'list' object has no attribute 'list'

In [ ]:
countries = [1,2,3,4,5,6,7,8,9]
print(countries[0:5])

countries_2 =['India', 'china','nepal', 'japan', 'srilanka']

countries_2   = countries.copy()

[1, 2, 3, 4, 5]

In [ ]:
countries_2

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
my_data = {'name':'nitin','age':37}

In [ ]:
my_data

{'name': 'nitin', 'age': 37}

In [ ]:
my_data

{'name': 'nitin', 'age': 37}

In [ ]:
my_data ['name']
my_data ['age']

37

In [33]:
my_data.keys()

dict_keys(['name', 'age'])

In [32]:
my_data

{'name': 'nitin', 'age': 37}

In [34]:
my_data.values()

dict_values(['nitin', 37])

In [40]:
age =14
if age>=18:
    print("you are and aduly")
elif age>=13:
    print("you are teenager")
else:
    print("you are a kid")

you are teenager

In [2]:
prescription = True
medicine_available = False

if prescription and medicine_available:
    print("Medicine can be sold.")
else:
    print("Cannot sell medicine.")

Cannot sell medicine.

In [5]:
age = 20

prescription = True

if age >= 18 and prescription:
    print("Customer is eligible.")
else:
    print("Customer is not eligible.")

Customer is eligible.

In [8]:
count = 1
while count <5:
    print(count)

    count+=1

1
2
3
4

In [13]:
my_data

{'name': 'nitin', 'age': 37}

In [16]:
for key ,values in my_data.items():
    print(key)
    print(values)

name
nitin
age
37

In [21]:
def sum_values (a, b):
    x = a-b
    return x

In [22]:
sum_values(100, 250)

-150

In [23]:
import os

In [24]:
os.getcwd()

'd:\\Sample-github'

In [25]:
os.listdir()

['.git',
 'profile picture.jpeg',
 'progit.pdf',
 'pythoncourse.ipynb',
 'pythoncourse.py',
 'README.md',
 'xyz']

In [26]:
os.mkdir('zyx')

In [1]:
import panda as pd 
import numpy as np

ModuleNotFoundError: No module named 'panda'

In [4]:
import pandas as pd
import numpy as np

In [10]:

data = np.array ([[1,4,5],[2,5,6],[3,6,7],[2,2,3]])
df = pd.DataFrame(data, index=['row1', 'row2', 'row3','row4'],
                 columns=['col1', 'col2','NITIN'])

In [11]:
df

      col1  col2  NITIN
row1     1     4      5
row2     2     5      6
row3     3     6      7
row4     2     2      3

In [12]:
data

array([[1, 4, 5],
       [2, 5, 6],
       [3, 6, 7],
       [2, 2, 3]])

In [13]:
data2 = [[1, 4], [2, 5], [3, 6]]

In [14]:
data2

[[1, 4], [2, 5], [3, 6]]

In [15]:
import pandas as pd

In [16]:
df=pd.read_csv("https://raw.githubusercontent.com/Nitin-Fulzele/Python-for-DataScience/refs/heads/main/python-for-data-science-main/02.Intro%20to%20Pandas/StudentsPerformance.csv")

In [17]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86